harnessApiVersion: '1.0'
type: APPLICATION_MANIFEST
gitFileConfig:
  branch: master
  connectorName: Harness Lab Kubernetes Deployment - huangb10
  filePath: cvlab
  useBranch: true
  useInlineServiceDefinition: false
storeType: Remote
